server:
  context-path: /sampleserver/v1
  port: 8090


custom:
  config:
    from:
      vault: ${secret.management.value}


spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@localhost:27017/vault-sample

endpoints:
  actuator:
    sensitive: false

management:
  security:
    enabled: false

