spring:
  profiles:
      active: git,vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jfbramlett/secret-management
          searchPaths: config-server
          order: 1
        vault:
          host: 172.17.0.2
          port: 8200
          scheme: http
          backend: secret
          order: 2


logging:
  level:
    spring.framework: DEBUG